# This file was generated by GoReleaser. DO NOT EDIT.
cask "markist-cli" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "cefa5e5ac3f5bc2cd11fc3345fb6c7fbc483ad36beeb20cfcabf75e66f85dd9a"
      url "https://github.com/jmbataller/markist/releases/download/v#{version}/markist-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2fd7d47711cc505fde0b2aa4d85babf29faa6b5ccd2a41896e34c0f5a686065a"
      url "https://github.com/jmbataller/markist/releases/download/v#{version}/markist-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6501677d075a6aa7f62764345df01cddf9afda26f4734a79c134dcf63cf910e5"
      url "https://github.com/jmbataller/markist/releases/download/v#{version}/markist-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c37eb611724c3f32c639ad669414cef9251edb8584f09baedcd55117cca82539"
      url "https://github.com/jmbataller/markist/releases/download/v#{version}/markist-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "markist-cli"
  desc "Markist CLI -- bookmarks and prompts from your terminal"
  homepage "https://markist.xyz"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "markist"
  manpage "man/markist.1"
  bash_completion "completions/markist.bash"
  fish_completion "completions/markist.fish"
  zsh_completion "completions/markist.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/markist"]
    end
  end

  # No zap stanza required
end
