# This file was generated by GoReleaser. DO NOT EDIT.
cask "markist-cli" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "f0cf39249ba730ebefc2ef0c4579811dae82bfdc9cdb064b24329a91a6a1d708"
      url "https://github.com/pragmatico/markist-cli/releases/download/v#{version}/markist-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "526ea812ac3848127cf6df3fbb0b3dbbc97850fbfc5079632e394d70321fc7ad"
      url "https://github.com/pragmatico/markist-cli/releases/download/v#{version}/markist-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3c82ab6f6f24e0bf932f75bf07a5c7b7443eb317cc00aca2a71b2d4943b605e7"
      url "https://github.com/pragmatico/markist-cli/releases/download/v#{version}/markist-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c4aaaebcac4cd3a0a06cd435fb8146ffa935c6ef70f567f5d0c4b6033fda25fb"
      url "https://github.com/pragmatico/markist-cli/releases/download/v#{version}/markist-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "markist-cli"
  desc "Markist CLI -- bookmarks and prompts from your terminal"
  homepage "https://markist.xyz"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "markist"
  manpage "man/markist.1"
  bash_completion "completions/markist.bash"
  fish_completion "completions/markist.fish"
  zsh_completion "completions/markist.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/markist"]
    end
  end

  # No zap stanza required
end
